### ISSUE TITLE
Feature request: Delete a specified value from a list

### ISSUE THREAD

**Issue by ben-g-** [pacha/cels#9]
Based on my reading of the README, the following operation is not supported:

_Delete a specified value from a list_

(as opposed to deleting the value at a specified index)

Here's one possible way that could look:
```
#input
list:
- a
- b
- c

# patch
list {deleteitem}: b

# output
list:
- a
- c
```

(I realize that a list can contain the same value multiple times, so that one would have to define the behavior in that case. For example, the behavior could be that every occurrence of the specified value is deleted; or that precisely the first occurrence of it is deleted; or that it's an error if the specified value occurs multiple times.)

What do you think? Is that a sensible feature? How feasible is it to implement?

**Comment by pacha** [comment]
Hi there @ben-g-,
Somehow I managed to mess up my notifications settings in GH and didn't see your message until now. Sorry for that.
That operation makes a lot of sense, I just implemented it as `delete_value` in @pacha/cels@2.5.4. I went for deleting all the occurrences of the value because deleting just the first one feels a bit arbitrary. I guess a more complex command could be added in the future to pass a count of occurrences to delete. But, in any case, the new `delete_value` is pretty simple and neat:
```yaml
# input
foo:
  - a
  - b
  - a

# patch
foo {delete_value}: a

# output
foo:
  - b
```
https://github.com/pacha/cels?tab=readme-ov-file#delete_value
Let me know if this works for you!

**Comment by ben-g-** [comment]
Thanks @pacha for implementing this feature!

Unfortunately, I guess I didn't think it through completely before requesting it, because:

One might want to delete multiple values from the same list. Given the current implementation, I guess that would look like this:
```
# input
foo:
  - a
  - b
  - c

# patch
foo {delete_value}: a
foo {delete_value}: c
```

... which doesn't work, because the patch is a mapping with duplicate keys.

Then again, I guess the same is true of inserting multiple values into the same list (without specifying target indices). That would entail having the key `foo {insert}` multiple times, which wouldn't work. Is that correct?

**Comment by pacha** [comment]
Hi again @ben-g-,

You're right. This situation is not related to deletions in particular. See my answer to the new ticket (#12). You can get the output that you were expecting with:
```yaml
# input
list:
- a
- b
- c

# patch
list {change}:
- operation: delete_value
  value: b
- operation: delete_value
  value: c

# output
list:
- a
```
